### ISSUE TITLE
Fails to compile with Vortex 6.6.2p2

### ISSUE THREAD

**Issue by quiccsmith** [PrismTech/opensplice-tools#1]
ash-4.1$ pwd
/home/asmith/Downloads/opensplice-tools-master
bash-4.1$ ls
common.c     LICENSE      porting.h  simpleidlpp        testtypeSacDcps.d  tglib.c
common.d     lsbuiltin.c  pubsub.c   testtypeDcps.h     testtypeSacDcps.h  tglib.h
common.h     lsbuiltin.d  pubsub.d   testtype.h     testtypeSplDcps.c
genreader.c  makefile     README.md  testtype.idl       testtypeSplDcps.d
idl2md       porting.c    ShapeType.idl  testtypeSacDcps.c  testtypeSplDcps.h

bash-4.1$ make
In file included from common.h:4:0,
                 from pubsub.c:31:
/proj/sw/3rdparty/PrismTech/Vortex_v2/Device/VortexOpenSplice/6.6.2p2/HDE/x86_64.linux/include/dcps/C/SAC/dds_dcps.h:21:20: fatal error: c_base.h: No such file or directory
 #include "c_base.h"
                    ^
compilation terminated.
make: **\* [pubsub.o] Error 1
bash-4.1$

**Comment by eboasson** [comment]
Looks like I forgot to add the "include/sys" directory to the include path, which strangely enough doesn't cause the same problem for me ... Anyway, I've pushed an update to the makefile that I believe will fix it.
